name: Test-Project
on: push
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Run test
              run: npm test
    build:
        needs: test
        runs-on: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Build the code
              run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                name: disFile
                path: dist
    deploy:
        needs: build
        runs-on: windows-latest
        steps:
            - name: Download artifactory
              uses: actions/download-artifact@v4
              with:
                name: distFile
            - name: List files
              run: ls
            - name: Deploy
              run: echo "Deploying the build files"
             

