name: Test-Project
on: push
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Run test
              run: npm test
    deploy:
        runs-on: windows-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Build the code
              run: npm run build
            - name: Deploy
              run: echo "Deploying the build file........."
             

